### ISSUE TITLE
Who is asking to change or remove the guardian? | In terms of keeping language inclusive, I think this is an area where we may not need the “specific relationship” question to be a required field.

### ISSUE THREAD

**Issue by nonprofittechy** [LemmaLegalConsulting/docassemble-CLAGuardianship#63]

**Comment by RamiLorca** [comment]
@nonprofittechy I kept the question as is for now because of the way some of the court forms are written. For the Petition for Removal of Guardian, it forces you to check a box for either "mother", "father", or "both" if you indicate you're filing as a parent. The Application for Appointment of Counsel pretty much does the same thing.

**Comment by nonprofittechy** [comment]
Basic language I would use:

The form asks if you are the mother, father, or both (meaning both mother and father consent). If you do not select one of the boxes, we will leave this box blank and just check the box "the parents"

**Comment by nonprofittechy** [comment]
Sent out a reminder follow-up email to Carolin who had connected to Probate and Family Court to see if our edited form was acceptable. If it is--we need to adjust a few additional forms to match.

**Comment by nonprofittechy** [comment]
See #110
